Fix LIBPATCH
canonical/loki-k8s-operator pull request #55
Opened 2021-12-07 21:01 UTC by Abuelodelanada

2021-12-07 21:04 UTC, mmanciop requested changes
Also the .pop please :-)`

2021-12-07 21:06 UTC, mmanciop approved these changes

2021-12-07 21:14 UTC, mmanciop submitted a review, later dismissed

2021-12-07 22:10 UTC, rbarry82 approved these changes

2021-12-08 02:10 UTC, sed-i approved these changes

2021-12-08 04:52 UTC, Abuelodelanada commented on lib/charms/loki_k8s/v0/loki_push_api.py
> +LIBPATCH = 6
Yes,

https://github.com/canonical/loki-k8s-operator/issues/54

2021-12-08 05:24 UTC, rbarry82 approved these changes

2021-12-08 09:20 UTC, simskij approved these changes

2021-12-08 09:20 UTC, merged